## freemarker缓存是否开启
## freemarker缓存是否开启
spring:
  freemarker:
    cache: false
  ## freemarker编码格式
  ## freemarker编码格式
    charset: UTF-8
  ## freemarker模板文件前缀
  ## freemarker模板文件前缀
    template-loader-path: classpath:/templates/
  ## freemarker模板文件后缀，注意这里后缀名是ftl
  ## freemarker模板文件后缀，注意这里后缀名.ftl
    suffix: .ftl
cacheRoot: D:\\code\\test
department:
  d1: document_name01
  d2: document_name02
  d3: document_name03
  d4: document_name04
